[package]
name = "rust-rocket"
version = "0.5.1"
authors = ["Tim Peters <mail@darksecond.nl>", "Lauri Gustafsson <me@gustafla.space>"]
license = "MIT"
description = """
A client implementation of GNU Rocket.
"""
repository = "https://github.com/darksecond/rust-rocket"
edition = "2018"

[dependencies]
bincode = "1.3.1"
byteorder = "1.4.2"
serde = { version = "1.0.119", features = ["derive"] }
thiserror = "1.0.23"
