[package]
name = "rust-rocket"
version = "0.3.6"
authors = ["Tim Peters <mail@darksecond.nl>", "Lauri Gustafsson <me@gustafla.space>"]
license = "MIT"
description = """
A client implementation of GNU Rocket.
"""
repository = "https://github.com/darksecond/rust-rocket"
edition = "2018"

[dependencies]
byteorder = "1.3.4"
thiserror = "1.0.22"
